In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')
%matplotlib inline

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
df = pd.read_csv("drive/MyDrive/Dataset/DataProcessesing/UDPLagProcess.csv")

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 191694 entries, 0 to 191693
Data columns (total 90 columns):
 #   Column                        Non-Null Count   Dtype
---  ------                        --------------   -----
 0   Unnamed: 0                    191694 non-null  int64
 1   Unnamed: 0.1                  191694 non-null  int64
 2   Unnamed: 0.1.1                191694 non-null  int64
 3   Flow ID                       191694 non-null  object
 4    Source IP                    191694 non-null  object
 5    Source Port                  191694 non-null  int64
 6    Destination IP               191694 non-null  object
 7    Destination Port             191694 non-null  int64
 8    Protocol                     191694 non-null  int64
 9    Timestamp                    191694 non-null  object
 10   Flow Duration                191694 non-null  int64
 11   Total Fwd Packets            191694 non-null  int64
 12   Total Backward Packets       191694 non-null  int64
 13  Total Length of Fwd Packets   191694 non-null  float64
 14   Total Length of Bwd Packets  191694 non-null  float64
 15   Fwd Packet Length Max        191694 non-null  float64
 16   Fwd Packet Length Min        191694 non-null  float64
 17   Fwd Packet Length Mean       191694 non-null  float64
 18   Fwd Packet Length Std        191694 non-null  float64
 19  Bwd Packet Length Max         191694 non-null  float64
 20   Bwd Packet Length Min        191694 non-null  float64
 21   Bwd Packet Length Mean       191694 non-null  float64
 22   Bwd Packet Length Std        191694 non-null  float64
 23  Flow Bytes/s                  191691 non-null  float64
 24   Flow Packets/s               191694 non-null  float64
 25   Flow IAT Mean                191694 non-null  float64
 26   Flow IAT Std                 191694 non-null  float64
 27   Flow IAT Max                 191694 non-null  float64
 28   Flow IAT Min                 191694 non-null  float64
 29  Fwd IAT Total                 191694 non-null  float64
 30   Fwd IAT Mean                 191694 non-null  float64
 31   Fwd IAT Std                  191694 non-null  float64
 32   Fwd IAT Max                  191694 non-null  float64
 33   Fwd IAT Min                  191694 non-null  float64
 34  Bwd IAT Total                 191694 non-null  float64
 35   Bwd IAT Mean                 191694 non-null  float64
 36   Bwd IAT Std                  191694 non-null  float64
 37   Bwd IAT Max                  191694 non-null  float64
 38   Bwd IAT Min                  191694 non-null  float64
 39  Fwd PSH Flags                 191694 non-null  int64
 40   Bwd PSH Flags                191694 non-null  int64
 41   Fwd URG Flags                191694 non-null  int64
 42   Bwd URG Flags                191694 non-null  int64
 43   Fwd Header Length            191694 non-null  int64
 44   Bwd Header Length            191694 non-null  int64
 45  Fwd Packets/s                 191694 non-null  float64
 46   Bwd Packets/s                191694 non-null  float64
 47   Min Packet Length            191694 non-null  float64
 48   Max Packet Length            191694 non-null  float64
 49   Packet Length Mean           191694 non-null  float64
 50   Packet Length Std            191694 non-null  float64
 51   Packet Length Variance       191694 non-null  float64
 52  FIN Flag Count                191694 non-null  int64
 53   SYN Flag Count               191694 non-null  int64
 54   RST Flag Count               191694 non-null  int64
 55   PSH Flag Count               191694 non-null  int64
 56   ACK Flag Count               191694 non-null  int64
 57   URG Flag Count               191694 non-null  int64
 58   CWE Flag Count               191694 non-null  int64
 59   ECE Flag Count               191694 non-null  int64
 60   Down/Up Ratio                191694 non-null  float64
 61   Average Packet Size          191694 non-null  float64
 62   Avg Fwd Segment Size         191694 non-null  float64
 63   Avg Bwd Segment Size         191694 non-null  float64
 64   Fwd Header Length.1          191694 non-null  int64
 65  Fwd Avg Bytes/Bulk            191694 non-null  int64
 66   Fwd Avg Packets/Bulk         191694 non-null  int64
 67   Fwd Avg Bulk Rate            191694 non-null  int64
 68   Bwd Avg Bytes/Bulk           191694 non-null  int64
 69   Bwd Avg Packets/Bulk         191694 non-null  int64
 70  Bwd Avg Bulk Rate             191694 non-null  int64
 71  Subflow Fwd Packets           191694 non-null  int64
 72   Subflow Fwd Bytes            191694 non-null  int64
 73   Subflow Bwd Packets          191694 non-null  int64
 74   Subflow Bwd Bytes            191694 non-null  int64
 75  Init_Win_bytes_forward        191694 non-null  int64
 76   Init_Win_bytes_backward      191694 non-null  int64
 77   act_data_pkt_fwd             191694 non-null  int64
 78   min_seg_size_forward         191694 non-null  int64
 79  Active Mean                   191694 non-null  float64
 80   Active Std                   191694 non-null  float64
 81   Active Max                   191694 non-null  float64
 82   Active Min                   191694 non-null  float64
 83  Idle Mean                     191694 non-null  float64
 84   Idle Std                     191694 non-null  float64
 85   Idle Max                     191694 non-null  float64
 86   Idle Min                     191694 non-null  float64
 87  SimillarHTTP                  191694 non-null  object
 88   Inbound                      191694 non-null  int64
 89   Label                        191694 non-null  object
dtypes: float64(45), int64(39), object(6)
memory usage: 131.6+ MB

In [ ]:
df.isna().sum()

Unnamed: 0        0
Unnamed: 0.1      0
Unnamed: 0.1.1    0
Flow ID           0
 Source IP        0
                 ..
 Idle Max         0
 Idle Min         0
SimillarHTTP      0
 Inbound          0
 Label            0
Length: 90, dtype: int64

In [ ]:
print("columns: ", len(df.columns))
df.columns

columns:  90

Index(['Unnamed: 0', 'Unnamed: 0.1', 'Unnamed: 0.1.1', 'Flow ID', ' Source IP',
       ' Source Port', ' Destination IP', ' Destination Port', ' Protocol',
       ' Timestamp', ' Flow Duration', ' Total Fwd Packets',
       ' Total Backward Packets', 'Total Length of Fwd Packets',
       ' Total Length of Bwd Packets', ' Fwd Packet Length Max',
       ' Fwd Packet Length Min', ' Fwd Packet Length Mean',
       ' Fwd Packet Length Std', 'Bwd Packet Length Max',
       ' Bwd Packet Length Min', ' Bwd Packet Length Mean',
       ' Bwd Packet Length Std', 'Flow Bytes/s', ' Flow Packets/s',
       ' Flow IAT Mean', ' Flow IAT Std', ' Flow IAT Max', ' Flow IAT Min',
       'Fwd IAT Total', ' Fwd IAT Mean', ' Fwd IAT Std', ' Fwd IAT Max',
       ' Fwd IAT Min', 'Bwd IAT Total', ' Bwd IAT Mean', ' Bwd IAT Std',
       ' Bwd IAT Max', ' Bwd IAT Min', 'Fwd PSH Flags', ' Bwd PSH Flags',
       ' Fwd URG Flags', ' Bwd URG Flags', ' Fwd Header Length',
       ' Bwd Header Length', 'Fwd Packets/s', ' Bwd Packets/s',
       ' Min Packet Length', ' Max Packet Length', ' Packet Length Mean',
       ' Packet Length Std', ' Packet Length Variance', 'FIN Flag Count',
       ' SYN Flag Count', ' RST Flag Count', ' PSH Flag Count',
       ' ACK Flag Count', ' URG Flag Count', ' CWE Flag Count',
       ' ECE Flag Count', ' Down/Up Ratio', ' Average Packet Size',
       ' Avg Fwd Segment Size', ' Avg Bwd Segment Size',
       ' Fwd Header Length.1', 'Fwd Avg Bytes/Bulk', ' Fwd Avg Packets/Bulk',
       ' Fwd Avg Bulk Rate', ' Bwd Avg Bytes/Bulk', ' Bwd Avg Packets/Bulk',
       'Bwd Avg Bulk Rate', 'Subflow Fwd Packets', ' Subflow Fwd Bytes',
       ' Subflow Bwd Packets', ' Subflow Bwd Bytes', 'Init_Win_bytes_forward',
       ' Init_Win_bytes_backward', ' act_data_pkt_fwd',
       ' min_seg_size_forward', 'Active Mean', ' Active Std', ' Active Max',
       ' Active Min', 'Idle Mean', ' Idle Std', ' Idle Max', ' Idle Min',
       'SimillarHTTP', ' Inbound', ' Label'],
      dtype='object')

In [ ]:
df.head(5)

,Unnamed: 0,Unnamed: 0.1,Unnamed: 0.1.1,Flow ID,Source IP,Source Port,Destination IP,Destination Port,Protocol,Timestamp,...,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,SimillarHTTP,Inbound,Label
0,0,0,445444,172.16.0.5-192.168.50.4-9429-9429-6,172.16.0.5,9429,192.168.50.4,9429,6,2018-11-03 11:36:28.607338,...,29.444864,52.0,1.0,1.202128e+07,6.253623e+06,18628035.0,6193840.0,0,1,Syn
1,1,1,113842,172.16.0.5-192.168.50.4-60224-60224-6,172.16.0.5,60224,192.168.50.4,60224,6,2018-11-03 11:36:28.607339,...,0.000000,1.0,1.0,2.066268e+07,1.169783e+07,28934293.0,12391060.0,0,1,Syn
2,2,2,176377,172.16.0.5-192.168.50.4-33827-11746-6,192.168.50.4,11746,172.16.0.5,33827,6,2018-11-03 11:36:28.607388,...,0.000000,0.0,0.0,0.000000e+00,0.000000e+00,0.0,0.0,0,0,Syn
3,3,3,24777,172.16.0.5-192.168.50.4-33828-1431-6,172.16.0.5,33828,192.168.50.4,1431,6,2018-11-03 11:36:28.607391,...,0.000000,0.0,0.0,0.000000e+00,0.000000e+00,0.0,0.0,0,1,Syn
4,4,4,85100,172.16.0.5-192.168.50.4-5311-5311-6,172.16.0.5,5311,192.168.50.4,5311,6,2018-11-03 11:36:28.607442,...,33.234019,48.0,1.0,1.191047e+07,1.849493e+06,13693985.0,10001398.0,0,1,Syn

In [ ]:
X=df.drop(['Unnamed: 0.1.1','Unnamed: 0','Unnamed: 0.1'],axis=1)
X.drop(['SimillarHTTP','Flow ID',' Source IP', ' Destination IP', ' Timestamp'],axis=1,inplace=True)

In [ ]:
X.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 191694 entries, 0 to 191693
Data columns (total 82 columns):
 #   Column                        Non-Null Count   Dtype
---  ------                        --------------   -----
 0    Source Port                  191694 non-null  int64
 1    Destination Port             191694 non-null  int64
 2    Protocol                     191694 non-null  int64
 3    Flow Duration                191694 non-null  int64
 4    Total Fwd Packets            191694 non-null  int64
 5    Total Backward Packets       191694 non-null  int64
 6   Total Length of Fwd Packets   191694 non-null  float64
 7    Total Length of Bwd Packets  191694 non-null  float64
 8    Fwd Packet Length Max        191694 non-null  float64
 9    Fwd Packet Length Min        191694 non-null  float64
 10   Fwd Packet Length Mean       191694 non-null  float64
 11   Fwd Packet Length Std        191694 non-null  float64
 12  Bwd Packet Length Max         191694 non-null  float64
 13   Bwd Packet Length Min        191694 non-null  float64
 14   Bwd Packet Length Mean       191694 non-null  float64
 15   Bwd Packet Length Std        191694 non-null  float64
 16  Flow Bytes/s                  191691 non-null  float64
 17   Flow Packets/s               191694 non-null  float64
 18   Flow IAT Mean                191694 non-null  float64
 19   Flow IAT Std                 191694 non-null  float64
 20   Flow IAT Max                 191694 non-null  float64
 21   Flow IAT Min                 191694 non-null  float64
 22  Fwd IAT Total                 191694 non-null  float64
 23   Fwd IAT Mean                 191694 non-null  float64
 24   Fwd IAT Std                  191694 non-null  float64
 25   Fwd IAT Max                  191694 non-null  float64
 26   Fwd IAT Min                  191694 non-null  float64
 27  Bwd IAT Total                 191694 non-null  float64
 28   Bwd IAT Mean                 191694 non-null  float64
 29   Bwd IAT Std                  191694 non-null  float64
 30   Bwd IAT Max                  191694 non-null  float64
 31   Bwd IAT Min                  191694 non-null  float64
 32  Fwd PSH Flags                 191694 non-null  int64
 33   Bwd PSH Flags                191694 non-null  int64
 34   Fwd URG Flags                191694 non-null  int64
 35   Bwd URG Flags                191694 non-null  int64
 36   Fwd Header Length            191694 non-null  int64
 37   Bwd Header Length            191694 non-null  int64
 38  Fwd Packets/s                 191694 non-null  float64
 39   Bwd Packets/s                191694 non-null  float64
 40   Min Packet Length            191694 non-null  float64
 41   Max Packet Length            191694 non-null  float64
 42   Packet Length Mean           191694 non-null  float64
 43   Packet Length Std            191694 non-null  float64
 44   Packet Length Variance       191694 non-null  float64
 45  FIN Flag Count                191694 non-null  int64
 46   SYN Flag Count               191694 non-null  int64
 47   RST Flag Count               191694 non-null  int64
 48   PSH Flag Count               191694 non-null  int64
 49   ACK Flag Count               191694 non-null  int64
 50   URG Flag Count               191694 non-null  int64
 51   CWE Flag Count               191694 non-null  int64
 52   ECE Flag Count               191694 non-null  int64
 53   Down/Up Ratio                191694 non-null  float64
 54   Average Packet Size          191694 non-null  float64
 55   Avg Fwd Segment Size         191694 non-null  float64
 56   Avg Bwd Segment Size         191694 non-null  float64
 57   Fwd Header Length.1          191694 non-null  int64
 58  Fwd Avg Bytes/Bulk            191694 non-null  int64
 59   Fwd Avg Packets/Bulk         191694 non-null  int64
 60   Fwd Avg Bulk Rate            191694 non-null  int64
 61   Bwd Avg Bytes/Bulk           191694 non-null  int64
 62   Bwd Avg Packets/Bulk         191694 non-null  int64
 63  Bwd Avg Bulk Rate             191694 non-null  int64
 64  Subflow Fwd Packets           191694 non-null  int64
 65   Subflow Fwd Bytes            191694 non-null  int64
 66   Subflow Bwd Packets          191694 non-null  int64
 67   Subflow Bwd Bytes            191694 non-null  int64
 68  Init_Win_bytes_forward        191694 non-null  int64
 69   Init_Win_bytes_backward      191694 non-null  int64
 70   act_data_pkt_fwd             191694 non-null  int64
 71   min_seg_size_forward         191694 non-null  int64
 72  Active Mean                   191694 non-null  float64
 73   Active Std                   191694 non-null  float64
 74   Active Max                   191694 non-null  float64
 75   Active Min                   191694 non-null  float64
 76  Idle Mean                     191694 non-null  float64
 77   Idle Std                     191694 non-null  float64
 78   Idle Max                     191694 non-null  float64
 79   Idle Min                     191694 non-null  float64
 80   Inbound                      191694 non-null  int64
 81   Label                        191694 non-null  object
dtypes: float64(45), int64(36), object(1)
memory usage: 119.9+ MB

In [ ]:
X.replace([np.inf, -np.inf], np.nan, inplace=True)
X.dropna(inplace=True)

In [ ]:
y=X[' Label']
X.drop([' Label'],axis=1,inplace=True)

In [ ]:
y.value_counts().sum()

179584

In [ ]:
X.head(5)

,Source Port,Destination Port,Protocol,Flow Duration,Total Fwd Packets,Total Backward Packets,Total Length of Fwd Packets,Total Length of Bwd Packets,Fwd Packet Length Max,Fwd Packet Length Min,...,min_seg_size_forward,Active Mean,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,Inbound
0,9429,9429,6,36063894,7,2,42.0,12.0,6.0,6.0,...,20,18.0,29.444864,52.0,1.0,1.202128e+07,6.253623e+06,18628035.0,6193840.0,1
1,60224,60224,6,44851366,8,4,48.0,24.0,6.0,6.0,...,20,1.0,0.000000,1.0,1.0,2.066268e+07,1.169783e+07,28934293.0,12391060.0,1
2,11746,33827,6,1,2,0,12.0,0.0,6.0,6.0,...,20,0.0,0.000000,0.0,0.0,0.000000e+00,0.000000e+00,0.0,0.0,0
4,5311,5311,6,35731470,8,2,48.0,12.0,6.0,6.0,...,20,24.5,33.234019,48.0,1.0,1.191047e+07,1.849493e+06,13693985.0,10001398.0,1
5,33829,32787,6,101,2,2,12.0,12.0,6.0,6.0,...,20,0.0,0.000000,0.0,0.0,0.000000e+00,0.000000e+00,0.0,0.0,1

In [ ]:
X.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 179584 entries, 0 to 191693
Data columns (total 81 columns):
 #   Column                        Non-Null Count   Dtype
---  ------                        --------------   -----
 0    Source Port                  179584 non-null  int64
 1    Destination Port             179584 non-null  int64
 2    Protocol                     179584 non-null  int64
 3    Flow Duration                179584 non-null  int64
 4    Total Fwd Packets            179584 non-null  int64
 5    Total Backward Packets       179584 non-null  int64
 6   Total Length of Fwd Packets   179584 non-null  float64
 7    Total Length of Bwd Packets  179584 non-null  float64
 8    Fwd Packet Length Max        179584 non-null  float64
 9    Fwd Packet Length Min        179584 non-null  float64
 10   Fwd Packet Length Mean       179584 non-null  float64
 11   Fwd Packet Length Std        179584 non-null  float64
 12  Bwd Packet Length Max         179584 non-null  float64
 13   Bwd Packet Length Min        179584 non-null  float64
 14   Bwd Packet Length Mean       179584 non-null  float64
 15   Bwd Packet Length Std        179584 non-null  float64
 16  Flow Bytes/s                  179584 non-null  float64
 17   Flow Packets/s               179584 non-null  float64
 18   Flow IAT Mean                179584 non-null  float64
 19   Flow IAT Std                 179584 non-null  float64
 20   Flow IAT Max                 179584 non-null  float64
 21   Flow IAT Min                 179584 non-null  float64
 22  Fwd IAT Total                 179584 non-null  float64
 23   Fwd IAT Mean                 179584 non-null  float64
 24   Fwd IAT Std                  179584 non-null  float64
 25   Fwd IAT Max                  179584 non-null  float64
 26   Fwd IAT Min                  179584 non-null  float64
 27  Bwd IAT Total                 179584 non-null  float64
 28   Bwd IAT Mean                 179584 non-null  float64
 29   Bwd IAT Std                  179584 non-null  float64
 30   Bwd IAT Max                  179584 non-null  float64
 31   Bwd IAT Min                  179584 non-null  float64
 32  Fwd PSH Flags                 179584 non-null  int64
 33   Bwd PSH Flags                179584 non-null  int64
 34   Fwd URG Flags                179584 non-null  int64
 35   Bwd URG Flags                179584 non-null  int64
 36   Fwd Header Length            179584 non-null  int64
 37   Bwd Header Length            179584 non-null  int64
 38  Fwd Packets/s                 179584 non-null  float64
 39   Bwd Packets/s                179584 non-null  float64
 40   Min Packet Length            179584 non-null  float64
 41   Max Packet Length            179584 non-null  float64
 42   Packet Length Mean           179584 non-null  float64
 43   Packet Length Std            179584 non-null  float64
 44   Packet Length Variance       179584 non-null  float64
 45  FIN Flag Count                179584 non-null  int64
 46   SYN Flag Count               179584 non-null  int64
 47   RST Flag Count               179584 non-null  int64
 48   PSH Flag Count               179584 non-null  int64
 49   ACK Flag Count               179584 non-null  int64
 50   URG Flag Count               179584 non-null  int64
 51   CWE Flag Count               179584 non-null  int64
 52   ECE Flag Count               179584 non-null  int64
 53   Down/Up Ratio                179584 non-null  float64
 54   Average Packet Size          179584 non-null  float64
 55   Avg Fwd Segment Size         179584 non-null  float64
 56   Avg Bwd Segment Size         179584 non-null  float64
 57   Fwd Header Length.1          179584 non-null  int64
 58  Fwd Avg Bytes/Bulk            179584 non-null  int64
 59   Fwd Avg Packets/Bulk         179584 non-null  int64
 60   Fwd Avg Bulk Rate            179584 non-null  int64
 61   Bwd Avg Bytes/Bulk           179584 non-null  int64
 62   Bwd Avg Packets/Bulk         179584 non-null  int64
 63  Bwd Avg Bulk Rate             179584 non-null  int64
 64  Subflow Fwd Packets           179584 non-null  int64
 65   Subflow Fwd Bytes            179584 non-null  int64
 66   Subflow Bwd Packets          179584 non-null  int64
 67   Subflow Bwd Bytes            179584 non-null  int64
 68  Init_Win_bytes_forward        179584 non-null  int64
 69   Init_Win_bytes_backward      179584 non-null  int64
 70   act_data_pkt_fwd             179584 non-null  int64
 71   min_seg_size_forward         179584 non-null  int64
 72  Active Mean                   179584 non-null  float64
 73   Active Std                   179584 non-null  float64
 74   Active Max                   179584 non-null  float64
 75   Active Min                   179584 non-null  float64
 76  Idle Mean                     179584 non-null  float64
 77   Idle Std                     179584 non-null  float64
 78   Idle Max                     179584 non-null  float64
 79   Idle Min                     179584 non-null  float64
 80   Inbound                      179584 non-null  int64
dtypes: float64(45), int64(36)
memory usage: 112.3 MB

In [ ]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
scaler.fit(X)
scaler.transform(X)

array([[0.1438839 , 0.14387732, 0.35294118, ..., 0.31543458, 0.10505646,
        1.        ],
       [0.9190014 , 0.91895933, 0.35294118, ..., 0.4899538 , 0.21017025,
        1.        ],
       [0.17924068, 0.51616693, 0.35294118, ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.98835683, 0.98831159, 0.35294118, ..., 0.20733245, 0.20767671,
        1.        ],
       [0.52581945, 0.69922942, 0.35294118, ..., 0.        , 0.        ,
        1.        ],
       [0.52583471, 0.28351263, 0.35294118, ..., 0.        , 0.        ,
        1.        ]])

In [ ]:
X.head()

,Source Port,Destination Port,Protocol,Flow Duration,Total Fwd Packets,Total Backward Packets,Total Length of Fwd Packets,Total Length of Bwd Packets,Fwd Packet Length Max,Fwd Packet Length Min,...,min_seg_size_forward,Active Mean,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,Inbound
0,9429,9429,6,36063894,7,2,42.0,12.0,6.0,6.0,...,20,18.0,29.444864,52.0,1.0,1.202128e+07,6.253623e+06,18628035.0,6193840.0,1
1,60224,60224,6,44851366,8,4,48.0,24.0,6.0,6.0,...,20,1.0,0.000000,1.0,1.0,2.066268e+07,1.169783e+07,28934293.0,12391060.0,1
2,11746,33827,6,1,2,0,12.0,0.0,6.0,6.0,...,20,0.0,0.000000,0.0,0.0,0.000000e+00,0.000000e+00,0.0,0.0,0
4,5311,5311,6,35731470,8,2,48.0,12.0,6.0,6.0,...,20,24.5,33.234019,48.0,1.0,1.191047e+07,1.849493e+06,13693985.0,10001398.0,1
5,33829,32787,6,101,2,2,12.0,12.0,6.0,6.0,...,20,0.0,0.000000,0.0,0.0,0.000000e+00,0.000000e+00,0.0,0.0,1

In [ ]:
from sklearn.feature_selection import chi2
chi=chi2(scaler.transform(X),y)

In [ ]:
chi

(array([3.59392746e+00, 1.57586604e+01, 3.63522360e+00, 7.68287342e+01,
        1.43425094e+01, 2.19242913e+01, 5.18012519e+01, 9.35701688e+01,
        4.02276857e+01, 1.05673892e+00, 1.34783643e+01, 6.43618571e+03,
        9.02046206e+01, 4.14564679e+01, 6.29832076e+01, 8.43922210e+03,
        1.09403946e-01, 9.93381396e+00, 4.04678020e+00, 1.60241411e+01,
        3.51412200e+01, 2.10544027e-01, 7.64076754e+01, 9.49337500e+00,
        2.19608255e+01, 3.50920739e+01, 4.35725349e-01, 1.21530710e+02,
        4.83581650e+01, 7.60006344e+01, 9.95957370e+01, 2.17670393e-01,
        6.17210000e+04,            nan,            nan,            nan,
        9.31885716e+00, 2.18735410e+01, 9.82500657e+00, 2.17618218e-01,
        9.12025277e-01, 9.09877082e+01, 1.45087644e+01, 1.04649755e+04,
        7.07463703e+03,            nan, 5.88130458e-03, 6.17210000e+04,
                   nan, 2.81145678e+01, 3.11613311e+04,            nan,
                   nan, 4.46650855e-01, 8.77152023e+00, 1.34783643e+01,
        6.29832076e+01, 9.31885716e+00,            nan,            nan,
                   nan,            nan,            nan,            nan,
        1.43425094e+01, 5.18012519e+01, 2.19242913e+01, 9.35701688e+01,
        1.46214035e+00, 2.42922893e+02, 1.58393443e+01, 7.81119489e-02,
        2.96059226e-03, 8.79390850e-02, 2.26615803e-02, 2.65521297e-01,
        4.34402848e+01, 7.43776743e-02, 3.52602445e+01, 5.42541896e+01,
        3.19976831e+01]),
 array([5.79910380e-02, 7.19577668e-05, 5.65690053e-02, 1.86445076e-18,
        1.52384770e-04, 2.83620989e-06, 6.14126395e-13, 3.92052218e-22,
        2.26022299e-10, 3.03960143e-01, 2.41330091e-04, 0.00000000e+00,
        2.14759951e-21, 1.20525134e-10, 2.08476402e-15, 0.00000000e+00,
        7.40823758e-01, 1.62269957e-03, 4.42556786e-02, 6.25399384e-05,
        3.06640825e-09, 6.46341335e-01, 2.30752662e-18, 2.06215140e-03,
        2.78272808e-06, 3.14478217e-09, 5.09192896e-01, 2.92439361e-28,
        3.55062728e-12, 2.83573612e-18, 1.86906324e-23, 6.40820724e-01,
        0.00000000e+00,            nan,            nan,            nan,
        2.26807414e-03, 2.91221825e-06, 1.72155086e-03, 6.40860740e-01,
        3.39577624e-01, 1.44567389e-21, 1.39508966e-04, 0.00000000e+00,
        0.00000000e+00,            nan, 9.38870427e-01, 0.00000000e+00,
                   nan, 1.14341933e-07, 0.00000000e+00,            nan,
                   nan, 5.03929716e-01, 3.05970322e-03, 2.41330091e-04,
        2.08476402e-15, 2.26807414e-03,            nan,            nan,
                   nan,            nan,            nan,            nan,
        1.52384770e-04, 6.14126395e-13, 2.83620989e-06, 3.92052218e-22,
        2.26589876e-01, 9.06567235e-55, 6.89537270e-05, 7.79872533e-01,
        9.56607456e-01, 7.66813716e-01, 8.80340459e-01, 6.06352072e-01,
        4.37096347e-11, 7.85066379e-01, 2.88460711e-09, 1.76161152e-13,
        1.54356565e-08]))

In [ ]:
Xcol=pd.DataFrame(X.columns)
Xcol

                     0
0          Source Port
1     Destination Port
2             Protocol
3        Flow Duration
4    Total Fwd Packets
..                 ...
76           Idle Mean
77            Idle Std
78            Idle Max
79            Idle Min
80             Inbound

[81 rows x 1 columns]

In [ ]:
chi2=pd.DataFrame(chi[0])
pval=pd.DataFrame(chi[1])

In [ ]:
result=pd.concat([Xcol,chi2,pval],axis=1)
result.columns =['Fitur','Chi2','P value']
result.dropna(inplace=True)

In [ ]:
result

                 Fitur       Chi2       P value
0          Source Port   3.593927  5.799104e-02
1     Destination Port  15.758660  7.195777e-05
2             Protocol   3.635224  5.656901e-02
3        Flow Duration  76.828734  1.864451e-18
4    Total Fwd Packets  14.342509  1.523848e-04
..                 ...        ...           ...
76           Idle Mean  43.440285  4.370963e-11
77            Idle Std   0.074378  7.850664e-01
78            Idle Max  35.260245  2.884607e-09
79            Idle Min  54.254190  1.761612e-13
80             Inbound  31.997683  1.543566e-08

[68 rows x 3 columns]

In [ ]:
df.to_csv("drive/MyDrive/Dataset/DataProcess/UDPLagDataProcessingWithChiSquare1.csv")